name: SCA

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  snyk-cli:
    uses: auth0/devsecops-tooling/.github/workflows/sca-scan.yml@main
    with:
      additional-arguments: "--exclude=README.md"
      python-version: "3.12"
    secrets: inherit
